# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professorsdb',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(choices=[(1, 'CSE'), (2, 'ECE'), (3, 'SOFTSKILLS'), (4, 'MATHEMATICS'), (5, 'CHEMISTRY'), (6, 'CIVIL'), (7, 'ELECTRICAL'), (8, 'PRODUCTION'), (9, 'META'), (10, 'MECHANICAL')], default=(2, 'ECE'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('Programme', models.CharField(choices=[(1, 'B.Tech'), (2, 'M.Tech')], default=(2, 'M.Tech'), max_length=20)),
                ('dept', models.CharField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'MECHANICAL'), (4, 'ELECTRICAL'), (5, 'META'), (6, 'ECE'), (7, 'PRODUCTION')], default=(2, 'CIVIL'), max_length=20)),
            ],
        ),
    ]
