# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='Programme',
            field=models.CharField(choices=[(1, 'B.Tech'), (2, 'M.Tech')], default='B.Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='dept',
            field=models.CharField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'MECHANICAL'), (4, 'ELECTRICAL'), (5, 'META'), (6, 'ECE'), (7, 'PRODUCTION')], default='CSE', max_length=20),
        ),
    ]
