# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sem_no', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=('1', '1'), max_length=1)),
                ('T1sub1', models.CharField(blank=True, max_length=2)),
                ('T1sub2', models.CharField(blank=True, max_length=2)),
                ('T1sub3', models.CharField(blank=True, max_length=2)),
                ('T1sub4', models.CharField(blank=True, max_length=2)),
                ('T1sub5', models.CharField(blank=True, max_length=2)),
                ('T1sub6', models.CharField(blank=True, max_length=2)),
                ('T2sub1', models.CharField(blank=True, max_length=2)),
                ('T2sub2', models.CharField(blank=True, max_length=2)),
                ('T2sub3', models.CharField(blank=True, max_length=2)),
                ('T2sub4', models.CharField(blank=True, max_length=2)),
                ('T2sub5', models.CharField(blank=True, max_length=2)),
                ('T2sub6', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'MECHANICAL'), (4, 'ECE'), (5, 'ELECTRICAL'), (6, 'META'), (7, 'PRODUCTION')], default='CSE', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectProff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_id', models.CharField(max_length=25)),
                ('branch', models.CharField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'MECHANICAL'), (4, 'ECE'), (5, 'ELECTRICAL'), (6, 'META'), (7, 'PRODUCTION')], default=('1', '1'), max_length=40)),
            ],
        ),
    ]
