# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsgms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=4)),
                ('cursem', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfWork',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('C1', models.CharField(blank=True, max_length=6)),
                ('C2', models.CharField(blank=True, max_length=6)),
                ('C3', models.CharField(blank=True, max_length=6)),
                ('C4', models.CharField(blank=True, max_length=6)),
                ('C5', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='SubjectProff',
        ),
    ]
